### PR TITLE
Feature/integration tests

### PR DESCRIPTION
**Pull request by cliff76**
Adds initial integration tests.

### CODE REVIEW

**Comment by aspittel** [comment]
This is awesome, thank you so much! I'm having some errors on my computer. I wonder if it's from my config?

```
    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    SyntaxError: /Users/alisonspittel/code/women-in-tech/src/App.test.js: Unexpected token (7:18)

       5 | it('renders without crashing', () => {
       6 |   const div = document.createElement('div');
    >  7 |   ReactDOM.render(<App />, div);
         |                   ^
       8 |   ReactDOM.unmountComponentAtNode(div);
       9 | });
      10 |

      at Parser.raise (node_modules/@babel/parser/lib/index.js:3939:15)
      at Parser.unexpected (node_modules/@babel/parser/lib/index.js:5248:16)
      at Parser.parseExprAtom (node_modules/@babel/parser/lib/index.js:6328:20)
      at Parser.parseExprSubscripts (node_modules/@babel/parser/lib/index.js:5924:21)
      at Parser.parseMaybeUnary (node_modules/@babel/parser/lib/index.js:5903:21)
      at Parser.parseExprOps (node_modules/@babel/parser/lib/index.js:5812:21)
      at Parser.parseMaybeConditional (node_modules/@babel/parser/lib/index.js:5784:21)
      at Parser.parseMaybeAssign (node_modules/@babel/parser/lib/index.js:5731:21)
      at Parser.parseExprListItem (node_modules/@babel/parser/lib/index.js:7003:18)
      at Parser.parseCallExpressionArguments (node_modules/@babel/parser/lib/index.js:6124:22)

 FAIL  src/specs/Main.spec.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    SyntaxError: /Users/alisonspittel/code/women-in-tech/src/specs/Main.spec.js: Unexpected token (17:20)

      15 |
      16 |   it("should render without crashing", () => {
    > 17 |     renderer.create(<App />);
         |                     ^
      18 |   });
      19 |
      20 |   it("should allow shallow rendering", () => {

      at Parser.raise (node_modules/@babel/parser/lib/index.js:3939:15)
      at Parser.unexpected (node_modules/@babel/parser/lib/index.js:5248:16)
      at Parser.parseExprAtom (node_modules/@babel/parser/lib/index.js:6328:20)
      at Parser.parseExprSubscripts (node_modules/@babel/parser/lib/index.js:5924:21)
      at Parser.parseMaybeUnary (node_modules/@babel/parser/lib/index.js:5903:21)
      at Parser.parseExprOps (node_modules/@babel/parser/lib/index.js:5812:21)
      at Parser.parseMaybeConditional (node_modules/@babel/parser/lib/index.js:5784:21)
      at Parser.parseMaybeAssign (node_modules/@babel/parser/lib/index.js:5731:21)
      at Parser.parseExprListItem (node_modules/@babel/parser/lib/index.js:7003:18)
      at Parser.parseCallExpressionArguments (node_modules/@babel/parser/lib/index.js:6124:22)
```

**Comment by cliff76** [comment]
Hmm.. It looks like the tests are running without React in scope. Make sure you do either `npm install` or `yarn install`. There were some conflicts. I just rebased it on the latest from your master. Try pulling branch again...

**Comment by cliff76** [comment]
I just gave this another run on my system. (Forgot to update the inline snapshot after rebasing.) I'm using node version 8.11.1 and everything runs okay. Again, make sure you're properly installing all dependencies via `npm install`. (I use yarn but feel free to substitute npm.)

**Comment by aspittel** [comment]
Awesome, that fixed it! Thank you so much!

**Pull request merged**
