### PR TITLE
Add aria labels to icons

### PR DESCRIPTION
**Pull request by twhite96**
I wasn't able to see the database in dev so please take a look at this to see if it's okay.

### CODE REVIEW

**Comment by aspittel** [comment]
Thank you so much for contributing @twhite96!! This is awesome.

For this situation, since the icons are links, we still want them to show up for screen readers.  I should have linked to lower down in the article, but I was thinking that we could add [title attributes](https://fontawesome.com/how-to-use/on-the-web/other-topics/accessibility#svg-semantic) to the icons in order to make them read properly for screen readers. (But an accessibility expert could totally correct me on that!)

**Comment by twhite96** [comment]
Okay. I'll take another look.

**Comment by twhite96** [comment]
Done!

**Comment by aspittel** [comment]
Awesome, thank you so much @twhite96!

**Pull request merged**
