### PR TITLE
 📖 DOC: link to create-guten-block

### PR DESCRIPTION
**Pull request by ahmadawais**
## Description

This PR adds a link to building WordPress Gutenberg blocks with React.js. 👍

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly.
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by aspittel** [comment]
Cool @ahmadawais! This looks like it's Wordpress specific, is it for learning React? These resources are mainly so people can be on boarded to the project. Thanks for contributing!

**Comment by ahmadawais** [comment]
@aspittel ah I missed that. I thought you were collecting resources. Silly me. It's for working with React in the context of WordPress. 👍

**Comment by aspittel** [comment]
Ah okay! Thanks anyways -- looks like a really cool resource!

**Comment by ahmadawais** [comment]
Thanks for saying that. I open sourced it early this year, have had its fair share of success. Try it out if you find yourself building Gutenberg blocks in WordPress which are React based.

**Pull request closed without merging**
